### ISSUE TITLE
demo 跑不起来

### ISSUE THREAD

**Issue by Ropynn** [xiaogliu/react-native-complete-demo#3]
你好，我clone下你的demo之后 npm install 以后， 运行安卓的时候 项目跑不起来，报错了，官网的demo是可以跑起来的。系统是win10的。报错内容如下：
![error](https://user-images.githubusercontent.com/30884964/40870182-400a1ac6-665c-11e8-8e51-1fcd998dbae7.jpg)
麻烦请问下是什么问题呢？

**Comment by Ropynn** [comment]
@xiaogliu 可以访问google服务，有稳定的梯子。我对于react-native完全是小白，之前没接触过， 我现在是直接clone你的代码下来的，没有做任何修改。应该怎么下载gradle呢?

**Comment by xiaogliu** [comment]
@Ropynn gradle 是在构建过程中自动下载的，我看你的报错显示 connect fail，应该是你的代理没有配置好：命令行工具和 android studio 中需要单独设置代理，不然他们还是没法访问墙外服务的（最好先在Android studio 中让项目跑起来，这样就证明各种依赖、虚拟机配置什么的都是ok的，后面再使用命令行启动）

我使用了[shadowsocksx-ng](https://github.com/shadowsocks/ShadowsocksX-NG/releases)，在它的设置里可以看到代理监听的地址，然后把地址填到 Android studio HTTP 代理中（setting -> appearance && behavior -> system settings -> http proxy），最后测试连接是否成功，成功后再更改 项目中 `android/gradle.properties` 这个文件的代理地址，然后再试下

![proxy](https://user-images.githubusercontent.com/15944323/40873012-2ab1d356-668b-11e8-86a0-74f8a997ded0.png)
![setting](https://user-images.githubusercontent.com/15944323/40873015-34c839fc-668b-11e8-9899-9ca1154e76df.png)

**Comment by Ropynn** [comment]
@xiaogliu 谢谢，之前那个问题解决了。不过现在出现个新问题。具体如下
![error1](https://user-images.githubusercontent.com/30884964/40895439-2217392c-67e2-11e8-9bfe-2af6a4cde642.jpg)

**Comment by xiaogliu** [comment]
@Ropynn 到目前为止的问题，都是原生开发的环境搭建、配置的问题，有些我也没遇到过，比如现在这个问题，所以我也不确定具体的解决方案（我对涉及原生开发的部分也不是特别熟。。。）

推荐的思路：1）将问题直接google下，看有没有解决方案；2）如果没有完全一致的问题及解决方案，按照搜索到的线索，**大概了解安卓原生开发的基本概念后**（比如 gradle 干嘛用，安卓虚拟机如何配置），根据错误提示配合类似问题及官方文档自己总结答案

对于这个项目推荐的使用方式：下载官方Demo，在官方Demo跑起来的前提下，根据这两篇文章 [开发 React Native APP —— 从改造官方Demo开始（一）](https://xiaogliu.github.io/2018/02/27/develop-react-native-app-1/)，[开发 React Native APP —— 从改造官方Demo开始（二）](https://xiaogliu.github.io/2018/02/27/develop-react-native-app-2/) 逐步添加功能，这样可避免依赖更新出现的问题，即便出问题，也容易定位

**Comment by Ropynn** [comment]
@xiaogliu 官方的demo是跑的起来的，有些其他的demo也跑的起来 ，不过那些demo我觉得都没有你这个好，但是你的这个demo跑不起来。我试试逐步添加功能吧。再次感谢你

**Comment by kevin611003** [comment]
下载了demo能跑，改了两个地方

**Comment by MoShenGuo** [comment]
![image](https://user-images.githubusercontent.com/21171688/48396626-0a407400-e756-11e8-86de-6d67e7784038.png)
缺失好多文件  根本跑不起来,还有App.js里有一个Rout是干嘛的怎么找不到呢

**Comment by Kirito511** [comment]
> @Ropynn gradle是在建造过程中自动下载的，我看你的报错显示connect fail，应该是你的代理没有配置好：命令行工具和android studio中需要单独设置代理，不然他们还是没法访问墙外服务的（最好先在Android studio中让项目跑起来，这样就证明各种依赖，虚拟机配置什么的都是ok的，后面再使用命令行启动）
> 
> 我使用了[shadowsocksx-ng](https://github.com/shadowsocks/ShadowsocksX-NG/releases)，在它的设置里可以看到代理监听的地址，然后把地址填到Android studio HTTP代理中（设置->外观和行为->系统设置-> http代理），最后测试连接是否成功，成功后再更改项目中`android/gradle.properties`这个文件的代理地址，然后再试下
> 
> ![代理](https://user-images.githubusercontent.com/15944323/40873012-2ab1d356-668b-11e8-86a0-74f8a997ded0.png)
> ![设置](https://user-images.githubusercontent.com/15944323/40873015-34c839fc-668b-11e8-9899-9ca1154e76df.png)

在android studio中配了那个地址 但是测试链接的时候连不上
